apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
        - name: stock-api
          image: widgetario/stock-api:1.0.0     # ← correct Part 1 image
          ports:
            - containerPort: 8080              # ← default port
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: stock-api-secret      # secret must point at products-db-secondary
                  key: POSTGRES_URL
          volumeMounts:
            - name: cache-volume
              mountPath: /cache               # preserve cache on restarts
      volumes:
        - name: cache-volume
          emptyDir: {}                         # ephemeral storage, survives restarts on same node
